/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

package org.dbarcarcel.Vista;
import org.dbarcarcel.modelo.Veterinaria;
import org.dbarcarcel.controlador.ControlDeVeterinaria;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author usuario
 */
public class VistaVerCliente extends javax.swing.JInternalFrame {
    
    public ControlDeVeterinaria controlador = ControlDeVeterinaria.getInstancia();  
     /**
     * Creates new form VistaVerCliente 
     */
    public VistaVerCliente() {
        initComponents();        
    }
    
    public void mostrarDatos(){
        String [] encabezados = {"Id","Nombre","Telefono","Cita"};
        int cantidadDeElementos = controlador.cantidadDeElementos();
        
        DefaultTableModel cabecera = new DefaultTableModel(encabezados,cantidadDeElementos);
        tablaDeDatosCliente.setModel(cabecera);
        TableModel listaDeDatos = tablaDeDatosCliente.getModel();
        
        for(int i=0; i<cantidadDeElementos; i++){
            Veterinaria veterinaria = controlador.getListaDeClientes().get(i);
            listaDeDatos.setValueAt(veterinaria.getId(), i, 0);
            listaDeDatos.setValueAt(veterinaria.getNombre(), i, 1);
            listaDeDatos.setValueAt(veterinaria.getTelefono(), i, 2);
            listaDeDatos.setValueAt(veterinaria.getCita(), i, 3);   
        }//for
    }
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTablaDeDatos = new javax.swing.JScrollPane();
        tablaDeDatosCliente = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        tablaDeDatosCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IdCliente", "Nombre", "Telefono", "Cita"
            }
        ));
        scrollTablaDeDatos.setViewportView(tablaDeDatosCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTablaDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(scrollTablaDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollTablaDeDatos;
    private javax.swing.JTable tablaDeDatosCliente;
    // End of variables declaration//GEN-END:variables

}
